# IMPORTING LIBS

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import kagglehub

d:\ANN_PTROJECT\penve\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# DOWNLOADING THE DATA

In [ ]:
'''path = kagglehub.dataset_download("umairaslam/dataset")

print("Path to dataset files:", path)'''

Downloading to C:\Users\Malik\.cache\kagglehub\datasets\umairaslam\dataset\1.archive...

100%|██████████| 32.5k/32.5k [00:00<00:00, 250kB/s]

Extracting files...
Path to dataset files: C:\Users\Malik\.cache\kagglehub\datasets\umairaslam\dataset\versions\1

# IMPORTING DATA

In [2]:
data=pd.read_excel("Data Analyst Task.xlsx")

In [3]:
data

,Purchase__basketValueGross,Purchase__purchaseType,Purchase__overallBasketSavings,Purchase__storeId,Purchase__paymentType__category,Purchase__paymentType__amount,Purchase__timeStamp,Purchase__basketValueNet,Purchase__says,Purchase__storeName,Purchase__storeFormat,Purchase__product__name,Purchase__product__quantity,Purchase__product__channel,Purchase__product__price
0,79.03,IN_STORE,3.17,3189.0,NaN,75.86,2021-10-30 18:37:36.766,75.86,NaN,SOUTHWARK,SuperStore,Koko Dairy Free Unsweetened Alternative Longli...,5.0,IN_STORE,1.50
1,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Bunched Spring Onions 100G,1.0,IN_STORE,0.37
2,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Finest Cheesecake Passion Fruit & Raspbe...,1.0,IN_STORE,4.00
3,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Mixed Sized Organic Eggs 6 Pack,1.0,IN_STORE,1.80
4,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Vanish Pet Expert Carpet Care Foam 600Ml,1.0,IN_STORE,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Oaty Rounds Biscuits 300G,1.0,IN_STORE,0.45
440,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Kraft Philadelphia Cheese 200 G Tub,2.0,IN_STORE,1.95
441,23.34,IN_STORE,6.39,3189.0,NaN,16.95,2021-02-14 14:50:31.071,16.95,NaN,SOUTHWARK,SuperStore,Tesco Garlic Baguette 205G,1.0,IN_STORE,0.90
442,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Elmlea Double Cream Alternative 284Ml,1.0,IN_STORE,0.89
443,...truncated.,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.sample(10)

,Purchase__basketValueGross,Purchase__purchaseType,Purchase__overallBasketSavings,Purchase__storeId,Purchase__paymentType__category,Purchase__paymentType__amount,Purchase__timeStamp,Purchase__basketValueNet,Purchase__says,Purchase__storeName,Purchase__storeFormat,Purchase__product__name,Purchase__product__quantity,Purchase__product__channel,Purchase__product__price
332,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Cucumber Whole Each,1.0,IN_STORE,0.43
426,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Pure Sunflower Oil 1L,1.0,IN_STORE,1.10
166,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Pork Ribs 700G,1.0,IN_STORE,4.20
116,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Finest Sweet Mini Peppers 220G,1.0,IN_STORE,1.50
308,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Finest Salami Milano 70G,1.0,IN_STORE,2.35
105,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Grahams Skyr Passion Fruit Mango & Papaya 450G,1.0,IN_STORE,0.99
299,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Filippo Berio Organic Extra Virgin Olive Oil 5...,1.0,IN_STORE,5.00
112,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Strawberries 400G,1.0,IN_STORE,2.00
22,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Tesco Choi Sum 200G,1.0,IN_STORE,1.20
36,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Galaxy Salted Caramel 135G,3.0,IN_STORE,0.99

In [5]:
x=data.iloc[:,:-1]